"use strict"
var express = require("express");
var MutationController = require("../controllers/mutation");
var router = express.Router();
//Rutas
router.get("/getAll", MutationController.getAll);
router.get("/getFasta", MutationController.getFasta);
router.get("/getMutations", MutationController.getMutations);
router.get("/getMutation/:mutationName?", MutationController.getMutation);
router.get("/getCases/:mutationName?", MutationController.getCases);
router.get("/getVHLTotal", MutationController.getVHLTotal);
router.get("/getEffectsTotal", MutationController.getEffectsTotal);
router.get("/getTypesTotal", MutationController.getTypesTotal);
router.get("/getMutationsbyFilters/:vhlTypes?/:effects?", MutationController.getMutationsbyFilters);
router.get("/getDownloadsbyFilters/:vhlTypes?/:effects?/:mutationType?/:molecule?/:risk?", MutationController.getDownloadsbyFilters);
router.get("/getNumberbyFilters/:vhlTypes?/:effects?/:mutationType?/:molecule?/:risk?", MutationController.getNumberbyFilters);
router.get("/getMissense", MutationController.getMissense);
router.get("/getVHLVenn", MutationController.getVHLVenn);
router.get("/getEffvenn", MutationController.getEffVenn);
router.get("/getSubstitutionMatrix", MutationController.getSubstitutionMatrix);
router.get("/getSubstitutionPosition", MutationController.getSubstitutionPosition);
router.get("/getProteinSequence", MutationController.getProteinSequence);
router.get("/getSankeyVHL", MutationController.getSankeyVHL);
router.get("/getSankeyEff", MutationController.getSankeyEff);
router.get("/getHistPositions", MutationController.getHistPositions);
router.get("/getVarSurface", MutationController.getVarSurface);
router.get("/getAllJson", MutationController.getAllJson);
router.get("/getHistVHL", MutationController.getHistVHL);
router.get("/getHistEff", MutationController.getHistEff);
router.get("/getResumeVHL", MutationController.getResumeVHL);
router.get("/getResumeEff", MutationController.getresumeEff);
router.get("/getPdb/:structure?", MutationController.getPdb);
router.get("/getSequenceWild", MutationController.getSequenceWild);
router.get("/getPdbExists/:structure?", MutationController.getPdbExists);
router.get("/getGrafo", MutationController.getGrafo);
module.exports = router;